/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'notes' : IDL.Opt(IDL.Text),
  'priority' : IDL.Text,
});

export const idlService = IDL.Service({
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Opt(Time), IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(Time), IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'notes' : IDL.Opt(IDL.Text),
    'priority' : IDL.Text,
  });
  
  return IDL.Service({
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Opt(Time), IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(Time),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };